function message1() {
    alert("DARK GREEN [NORMAL OU GREAT PASSWORD] [LOW LEVEL --> INTERMEDIARY LEVEL]")
    alert("LIGHT GREEN [NORMAL OU SPECIAL PASSWORD] [INTERMEDIARY LEVEL --> STRONGEST LEVEL]")
    alert("ORANGE [POWERFUL PASSWORD] [STRONGEST LEVEL --> MILITARY LEVEL]")
    alert("GREEN [MILITARY PASSWORD] [MILITARY LEVEL --> GOD LEVEL]")
    alert("PURPLE [GODNESS PASSWORD VERY POWERFUL AND STRONG] [GOD LEVEL --> IMPOSSIBLE LEVEL]")
    alert("RED [UNBREAKABLE PASSWORD, VERY BIG AND COMPLEX] [(UNBREAKBALE TO IMPOSSIBLE) LEVEL --> IAAS LEVEL [INFRASTRUCTURE PASSWORD] LEVEL]")
    alert("BLACK & WHITE [INFRASTRUCTURE LEVEL, UNBREAKABLE, COMPLEX, GIANT PASSWORDS,] [THIS IS THE MOST STRONGEST PASSWORDS O_O]")
}