function message2() {
    alert("UPDATE: WINDOWS CMD PROMPT FOR PASSWORD CREATED")
    alert("UPDATE: BUG FIXES! [CSS ISSUE] & TWO NEW BUTTONS !")
    alert("SOON: NEW PASSWORDS FOR THE PASSWORD CREATION !")
}